import type {
  ApplianceProduct,
  CategoryMenuItem,
  HeroBanner,
  SubBanner,
  TrustBadgeItem,
  CategoryTabItem,
} from './types'

export const MOCK_CATEGORY_MENU: CategoryMenuItem[] = [
  {
    id: 'cat-tv',
    name: 'Tivi - Âm Thanh',
    slug: 'tivi-loa',
    icon: '📺',
    badgeText: 'HOT',
    subcategories: ['Tivi OLED / QLED', 'Smart Tivi 4K', 'Loa Soundbar', 'Dàn Karaoke gia đình'],
  },
  {
    id: 'cat-fridge',
    name: 'Tủ Lạnh - Tủ Đông',
    slug: 'tu-lanh',
    icon: '❄️',
    subcategories: ['Tủ lạnh Side-by-side', 'Tủ lạnh 4 cánh Multidoor', 'Tủ lạnh Inverter', 'Tủ đông gia đình'],
  },
  {
    id: 'cat-washing',
    name: 'Máy Giặt - Máy Sấy',
    slug: 'may-giat',
    icon: '🧺',
    subcategories: ['Máy giặt cửa ngang', 'Máy giặt cửa trên', 'Máy sấy thông hơi', 'Máy sấy bơm nhiệt Heatpump'],
  },
  {
    id: 'cat-ac',
    name: 'Điều Hòa - Lọc Khí',
    slug: 'dieu-hoa',
    icon: '💨',
    subcategories: ['Điều hòa 1 chiều Inverter', 'Điều hòa 2 chiều', 'Máy lọc không khí', 'Quạt điều hòa làm mát'],
  },
  {
    id: 'cat-kitchen',
    name: 'Gia Dụng - Bếp',
    slug: 'gia-dung',
    icon: '🍳',
    badgeText: '-40%',
    subcategories: ['Nồi chiên không dầu', 'Bếp từ đôi Inverter', 'Nồi cơm điện cao tần', 'Lò vi sóng nướng'],
  },
  {
    id: 'cat-digital',
    name: 'Điện Thoại - Laptop',
    slug: 'dien-tu',
    icon: '📱',
    subcategories: ['Điện thoại thông minh', 'Laptop văn phòng & Gaming', 'Máy tính bảng', 'Phụ kiện cáp sạc'],
  },
]

export const MOCK_HERO_BANNERS: HeroBanner[] = [
  {
    id: 'banner-1',
    title: 'Đại Tiệc Tivi QLED 4K Thế Hệ Mới',
    subtitle: 'Đỉnh cao hình ảnh rực rỡ, tích hợp AI Upscaling và âm thanh vòm Dolby Atmos',
    tagline: 'SIÊU PHẨM CÔNG NGHỆ 2026',
    imageUrl: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=1200&auto=format&fit=crop&q=80',
    linkUrl: '/browse?categoryId=tivi-loa',
    alt: 'Banner Tivi Samsung QLED 4K ưu đãi mùa lễ hội',
  },
  {
    id: 'banner-2',
    title: 'Tủ Lạnh Side-By-Side Siêu Tiết Kiệm Điện',
    subtitle: 'Công nghệ bảo quản chân không ngăn mềm, cấp đông siêu tốc, Inverter 5 sao',
    tagline: 'TIỆN NGHI GIA ĐÌNH VIỆT',
    imageUrl: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=1200&auto=format&fit=crop&q=80',
    linkUrl: '/browse?categoryId=tu-lanh',
    alt: 'Banner Tủ Lạnh Inverter bảo hành 10 năm máy nén',
  },
  {
    id: 'banner-3',
    title: 'Máy Giặt Cửa Ngang AI Khử Khuẩn 99.9%',
    subtitle: 'Giặt hơi nước thông minh Steam+, bảo vệ sợi vải tối ưu, vận hành êm ái',
    tagline: 'CHĂM SÓC TOÀN DIỆN',
    imageUrl: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=1200&auto=format&fit=crop&q=80',
    linkUrl: '/browse?categoryId=may-giat',
    alt: 'Banner Máy giặt thông minh AI EcoInverter',
  },
]

export const MOCK_SUB_BANNERS: [SubBanner, SubBanner] = [
  {
    id: 'sub-banner-installment',
    title: 'Đặc Quyền Trả Góp 0%',
    badge: 'DUYỆT NHANH 5 PHÚT',
    highlight: 'Trả trước 0đ • Không phí ẩn • Hỗ trợ mọi ngân hàng',
    imageUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&auto=format&fit=crop&q=80',
    linkUrl: '/browse?filter=installment',
    alt: 'Banner ưu đãi mua sắm trả góp lãi suất 0%',
  },
  {
    id: 'sub-banner-tradein',
    title: 'Thu Cũ Đổi Mới Lên Đời',
    badge: 'TRỢ GIÁ 3 TRIỆU',
    highlight: 'Thu mọi dòng máy cũ • Định giá tại nhà • Nhận quà khủng',
    imageUrl: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=600&auto=format&fit=crop&q=80',
    linkUrl: '/browse?filter=trade-in',
    alt: 'Banner chương trình thu cũ đổi mới điện máy trợ giá hấp dẫn',
  },
]

export const MOCK_TRUST_BADGES: TrustBadgeItem[] = [
  {
    id: 'trust-1',
    icon: '⚡',
    title: 'Giao siêu tốc 2 giờ',
    subtitle: 'Miễn phí nội thành, hẹn giờ chuẩn xác',
  },
  {
    id: 'trust-2',
    icon: '🛠️',
    title: 'Lắp đặt miễn phí tận nhà',
    subtitle: 'Kỹ thuật viên chuyên nghiệp, tận tâm',
  },
  {
    id: 'trust-3',
    icon: '🔄',
    title: 'Lỗi 1 đổi 1 trong 30 ngày',
    subtitle: 'Thủ tục nhanh gọn cho lỗi phần cứng',
  },
  {
    id: 'trust-4',
    icon: '🛡️',
    title: 'Bảo hành chính hãng 100%',
    subtitle: 'Kích hoạt bảo hành điện tử chính hãng',
  },
]

export const MOCK_CATEGORY_TABS: CategoryTabItem[] = [
  { id: 'tab-all', name: 'Tất Cả Sản Phẩm', slug: 'all' },
  { id: 'tab-tv', name: 'Tivi - Loa', slug: 'tivi-loa' },
  { id: 'tab-fridge', name: 'Tủ Lạnh', slug: 'tu-lanh' },
  { id: 'tab-washing', name: 'Máy Giặt', slug: 'may-giat' },
  { id: 'tab-ac', name: 'Điều Hòa', slug: 'dieu-hoa' },
  { id: 'tab-kitchen', name: 'Gia Dụng Bếp', slug: 'gia-dung' },
  { id: 'tab-digital', name: 'Thiết Bị Số', slug: 'dien-tu' },
]

export const MOCK_APPLIANCE_PRODUCTS: ApplianceProduct[] = [
  {
    id: 'appliance-1',
    name: 'Smart Tivi Neo QLED 4K 55 inch Samsung QA55QN85D',
    modelNumber: 'QA55QN85DBXXV',
    brand: 'Samsung',
    slug: 'smart-tivi-neo-qled-4k-55-inch-samsung-qa55qn85d',
    imageUrl: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&auto=format&fit=crop&q=80',
    originalPrice: 28900000,
    salePrice: 21490000,
    discountPercent: 26,
    installmentBadge: 'Trả góp 0%',
    energyRating: 5,
    giftNote: 'Tặng Loa thanh Soundbar trị giá 3.500.000đ',
    specs: [
      { key: 'Kích thước', value: '55 inch 4K' },
      { key: 'Tần số quét', value: '120 Hz' },
      { key: 'Công nghệ', value: 'Quantum Matrix Neo QLED' },
    ],
    stockProgress: { sold: 34, total: 50 },
    categorySlug: 'tivi-loa',
    isHotDeal: true,
  },
  {
    id: 'appliance-2',
    name: 'Tủ lạnh LG Inverter 635 Lít Side-By-Side GR-D257JS',
    modelNumber: 'GR-D257JS',
    brand: 'LG',
    slug: 'tu-lanh-lg-inverter-635-lit-side-by-side-gr-d257js',
    imageUrl: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=600&auto=format&fit=crop&q=80',
    originalPrice: 34990000,
    salePrice: 24890000,
    discountPercent: 29,
    installmentBadge: 'Trả góp 0%',
    energyRating: 5,
    giftNote: 'Tặng Nồi chiên không dầu Lock&Lock 5.2L',
    specs: [
      { key: 'Dung tích', value: '635 Lít' },
      { key: 'Động cơ', value: 'Linear Inverter tiết kiệm điện' },
      { key: 'Tiện ích', value: 'Lấy nước & đá ngoài tự động' },
    ],
    stockProgress: { sold: 19, total: 25 },
    categorySlug: 'tu-lanh',
    isHotDeal: true,
  },
  {
    id: 'appliance-3',
    name: 'Máy giặt lồng ngang Electrolux UltimateCare 900 10kg',
    modelNumber: 'EWF1042R7SB',
    brand: 'Electrolux',
    slug: 'may-giat-electrolux-ultimatecare-900-10kg-ewf1042r7sb',
    imageUrl: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=600&auto=format&fit=crop&q=80',
    originalPrice: 17490000,
    salePrice: 12990000,
    discountPercent: 26,
    installmentBadge: 'Trả góp 0%',
    energyRating: 5,
    giftNote: 'Tặng Giàn phơi thông minh + Nước giặt OMO 4.2kg',
    specs: [
      { key: 'Khối lượng', value: '10 kg giặt' },
      { key: 'Công nghệ', value: 'SensorWash cảm biến vết bẩn' },
      { key: 'Động cơ', value: 'EcoInverter vận hành êm' },
    ],
    stockProgress: { sold: 42, total: 50 },
    categorySlug: 'may-giat',
    isHotDeal: true,
  },
  {
    id: 'appliance-4',
    name: 'Điều hòa Daikin Inverter 1 HP FTKB25YVMV',
    modelNumber: 'FTKB25YVMV',
    brand: 'Daikin',
    slug: 'dieu-hoa-daikin-inverter-1-hp-ftkb25yvmv',
    imageUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&auto=format&fit=crop&q=80',
    originalPrice: 11590000,
    salePrice: 9490000,
    discountPercent: 18,
    installmentBadge: 'Trả góp 0%',
    energyRating: 5,
    giftNote: 'Miễn phí công lắp đặt + 5m ống đồng',
    specs: [
      { key: 'Công suất', value: '1 HP (9.000 BTU)' },
      { key: 'Khử mùi', value: 'Phin lọc Enzyme Blue tích hợp PM2.5' },
      { key: 'Gas lạnh', value: 'R32 thân thiện môi trường' },
    ],
    stockProgress: { sold: 68, total: 80 },
    categorySlug: 'dieu-hoa',
  },
  {
    id: 'appliance-5',
    name: 'Google Tivi Sony 4K 65 inch KD-65X77L',
    modelNumber: 'KD-65X77L',
    brand: 'Sony',
    slug: 'google-tivi-sony-4k-65-inch-kd-65x77l',
    imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&auto=format&fit=crop&q=80',
    originalPrice: 20900000,
    salePrice: 15490000,
    discountPercent: 26,
    installmentBadge: 'Trả góp 0%',
    energyRating: 5,
    giftNote: 'Gói ứng dụng VieON VIP + Galaxy Play 12 tháng',
    specs: [
      { key: 'Kích thước', value: '65 inch 4K' },
      { key: 'Bộ xử lý', value: '4K X-Reality PRO nâng cấp nét' },
      { key: 'Âm thanh', value: 'X-Balanced Speaker 20W' },
    ],
    stockProgress: { sold: 27, total: 40 },
    categorySlug: 'tivi-loa',
  },
  {
    id: 'appliance-6',
    name: 'Nồi chiên không dầu kết hợp hấp Philips 7.2L HD9880/90',
    modelNumber: 'HD9880/90',
    brand: 'Philips',
    slug: 'noi-chien-khong-dau-philips-7-2l-hd9880-90',
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&auto=format&fit=crop&q=80',
    originalPrice: 7990000,
    salePrice: 5690000,
    discountPercent: 29,
    energyRating: 5,
    giftNote: 'Tặng Bộ dao làm bếp Đức 5 món cao cấp',
    specs: [
      { key: 'Dung tích', value: '7.2 Lít (chiên gà nguyên con)' },
      { key: 'Công nghệ', value: 'Rapid CombiAir đối lưu kép' },
      { key: 'Công suất', value: '2200 W' },
    ],
    stockProgress: { sold: 45, total: 60 },
    categorySlug: 'gia-dung',
    isHotDeal: true,
  },
  {
    id: 'appliance-7',
    name: 'Tủ lạnh Panasonic Inverter 417 Lít NR-BX471GPKV',
    modelNumber: 'NR-BX471GPKV',
    brand: 'Panasonic',
    slug: 'tu-lanh-panasonic-inverter-417-lit-nr-bx471gpkv',
    imageUrl: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=600&auto=format&fit=crop&q=80',
    originalPrice: 19490000,
    salePrice: 15990000,
    discountPercent: 18,
    installmentBadge: 'Trả góp 0%',
    energyRating: 5,
    giftNote: 'Tặng Máy xay sinh tố Panasonic đa năng',
    specs: [
      { key: 'Dung tích', value: '417 Lít' },
      { key: 'Ngăn mềm', value: 'Prime Fresh -3°C nấu ngay không rã đông' },
      { key: 'Kháng khuẩn', value: 'Công nghệ Nanoe-X khử mùi 99.99%' },
    ],
    stockProgress: { sold: 16, total: 30 },
    categorySlug: 'tu-lanh',
  },
  {
    id: 'appliance-8',
    name: 'Máy giặt sấy lồng ngang LG AI DD 11kg / sấy 7kg FV1411D4W',
    modelNumber: 'FV1411D4W',
    brand: 'LG',
    slug: 'may-giat-say-lg-ai-dd-11kg-say-7kg-fv1411d4w',
    imageUrl: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=600&auto=format&fit=crop&q=80',
    originalPrice: 21990000,
    salePrice: 16290000,
    discountPercent: 26,
    installmentBadge: 'Trả góp 0%',
    energyRating: 5,
    giftNote: 'Tặng Bàn là hơi nước đứng cầm tay Philips',
    specs: [
      { key: 'Khối lượng', value: 'Giặt 11 kg + Sấy 7 kg' },
      { key: 'Công nghệ', value: 'AI DD bảo vệ sợi vải thêm 18%' },
      { key: 'Tốc độ vắt', value: '1400 vòng/phút' },
    ],
    stockProgress: { sold: 29, total: 35 },
    categorySlug: 'may-giat',
  },
]
