import type {
  ApplianceProduct,
  CategoryMenuItem,
  HeroBanner,
  SubBanner,
  TrustBadgeItem,
  CategoryTabItem,
} from './types'

export const MOCK_CATEGORY_MENU: CategoryMenuItem[] = [
  {
    id: 'cat-tv',
    name: 'Tivi - Âm Thanh',
    slug: 'tivi-loa',
    icon: '📺',
    badgeText: 'HOT',
    subcategories: ['Tivi OLED / QLED', 'Smart Tivi 4K', 'Loa Soundbar', 'Dàn Karaoke gia đình'],
  },
  {
    id: 'cat-fridge',
    name: 'Tủ Lạnh - Tủ Đông',
    slug: 'tu-lanh',
    icon: '❄️',
    subcategories: ['Tủ lạnh Side-by-side', 'Tủ lạnh 4 cánh Multidoor', 'Tủ lạnh Inverter', 'Tủ đông gia đình'],
  },
  {
    id: 'cat-washing',
    name: 'Máy Giặt - Máy Sấy',
    slug: 'may-giat',
    icon: '🧺',
    subcategories: ['Máy giặt cửa ngang', 'Máy giặt cửa trên', 'Máy sấy thông hơi', 'Máy sấy bơm nhiệt Heatpump'],
  },
  {
    id: 'cat-ac',
    name: 'Điều Hòa - Lọc Khí',
    slug: 'dieu-hoa',
    icon: '💨',
    subcategories: ['Điều hòa 1 chiều Inverter', 'Điều hòa 2 chiều', 'Máy lọc không khí', 'Quạt điều hòa làm mát'],
  },
  {
    id: 'cat-kitchen',
    name: 'Gia Dụng - Bếp',
    slug: 'gia-dung',
    icon: '🍳',
    badgeText: '-40%',
    subcategories: ['Nồi chiên không dầu', 'Bếp từ đôi Inverter', 'Nồi cơm điện cao tần', 'Lò vi sóng nướng'],
  },
  {
    id: 'cat-digital',
    name: 'Điện Thoại - Laptop',
    slug: 'dien-tu',
    icon: '📱',
    subcategories: ['Điện thoại thông minh', 'Laptop văn phòng & Gaming', 'Máy tính bảng', 'Phụ kiện cáp sạc'],
  },
]

export const MOCK_HERO_BANNERS: HeroBanner[] = [
  {
    id: 'banner-1',
    title: 'Đại Tiệc Tivi QLED 4K Thế Hệ Mới',
    subtitle: 'Đỉnh cao hình ảnh rực rỡ, tích hợp AI Upscaling và âm thanh vòm Dolby Atmos',
    tagline: 'SIÊU PHẨM CÔNG NGHỆ 2026',
    imageUrl: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=1200&auto=format&fit=crop&q=80',
    linkUrl: '/browse?categoryId=tivi-loa',
    alt: 'Banner Tivi Samsung QLED 4K ưu đãi mùa lễ hội',
  },
  {
    id: 'banner-2',
    title: 'Tủ Lạnh Side-By-Side Siêu Tiết Kiệm Điện',
    subtitle: 'Công nghệ bảo quản chân không ngăn mềm, cấp đông siêu tốc, Inverter 5 sao',
    tagline: 'TIỆN NGHI GIA ĐÌNH VIỆT',
    imageUrl: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=1200&auto=format&fit=crop&q=80',
    linkUrl: '/browse?categoryId=tu-lanh',
    alt: 'Banner Tủ Lạnh Inverter bảo hành 10 năm máy nén',
  },
  {
    id: 'banner-3',
    title: 'Máy Giặt Cửa Ngang AI Khử Khuẩn 99.9%',
    subtitle: 'Giặt hơi nước thông minh Steam+, bảo vệ sợi vải tối ưu, vận hành êm ái',
    tagline: 'CHĂM SÓC TOÀN DIỆN',
    imageUrl: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=1200&auto=format&fit=crop&q=80',
    linkUrl: '/browse?categoryId=may-giat',
    alt: 'Banner Máy giặt thông minh AI EcoInverter',
  },
]

export const MOCK_SUB_BANNERS: [SubBanner, SubBanner] = [
  {
    id: 'sub-banner-installment',
    title: 'Đặc Quyền Trả Góp 0%',
    badge: 'DUYỆT NHANH 5 PHÚT',
    highlight: 'Trả trước 0đ • Không phí ẩn • Hỗ trợ mọi ngân hàng',
    imageUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&auto=format&fit=crop&q=80',
    linkUrl: '/browse?filter=installment',
    alt: 'Banner ưu đãi mua sắm trả góp lãi suất 0%',
  },
  {
    id: 'sub-banner-tradein',
    title: 'Thu Cũ Đổi Mới Lên Đời',
    badge: 'TRỢ GIÁ 3 TRIỆU',
    highlight: 'Thu mọi dòng máy cũ • Định giá tại nhà • Nhận quà khủng',
    imageUrl: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=600&auto=format&fit=crop&q=80',
    linkUrl: '/browse?filter=trade-in',
    alt: 'Banner chương trình thu cũ đổi mới điện máy trợ giá hấp dẫn',
  },
]

export const MOCK_TRUST_BADGES: TrustBadgeItem[] = [
  {
    id: 'trust-1',
    icon: '⚡',
    title: 'Giao siêu tốc 2 giờ',
    subtitle: 'Miễn phí nội thành, hẹn giờ chuẩn xác',
  },
  {
    id: 'trust-2',
    icon: '🛠️',
    title: 'Lắp đặt miễn phí tận nhà',
    subtitle: 'Kỹ thuật viên chuyên nghiệp, tận tâm',
  },
  {
    id: 'trust-3',
    icon: '🔄',
    title: 'Lỗi 1 đổi 1 trong 30 ngày',
    subtitle: 'Thủ tục nhanh gọn cho lỗi phần cứng',
  },
  {
    id: 'trust-4',
    icon: '🛡️',
    title: 'Bảo hành chính hãng 100%',
    subtitle: 'Kích hoạt bảo hành điện tử chính hãng',
  },
]

export const MOCK_CATEGORY_TABS: CategoryTabItem[] = [
  { id: 'tab-all', name: 'Tất Cả Sản Phẩm', slug: 'all' },
  { id: 'tab-tv', name: 'Tivi - Loa', slug: 'tivi-loa' },
  { id: 'tab-fridge', name: 'Tủ Lạnh', slug: 'tu-lanh' },
  { id: 'tab-washing', name: 'Máy Giặt', slug: 'may-giat' },
  { id: 'tab-ac', name: 'Điều Hòa', slug: 'dieu-hoa' },
  { id: 'tab-kitchen', name: 'Gia Dụng Bếp', slug: 'gia-dung' },
  { id: 'tab-digital', name: 'Thiết Bị Số', slug: 'dien-tu' },
]

export const MOCK_APPLIANCE_PRODUCTS: ApplianceProduct[] = [
  {
    id: 'appliance-1',
    name: 'Samsung Neo QLED 4K 65 inch QA65QN90C',
    modelNumber: 'QA65QN90C',
    brand: 'Samsung',
    slug: 'samsung-neo-qled-4k-65-inch-qa65qn90c',
    imageUrl: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&auto=format&fit=crop&q=80',
    originalPrice: 52990000,
    salePrice: 45990000,
    discountPercent: 13,
    installmentBadge: 'Trả góp 0%',
    energyRating: 5,
    giftNote: 'Tặng Loa thanh Soundbar trị giá 3.500.000đ',
    specs: [
      { key: 'Kích thước', value: '65 inch 4K' },
      { key: 'Tần số quét', value: '120 Hz' },
      { key: 'Công nghệ', value: 'Quantum Matrix mini LED' },
    ],
    stockProgress: { sold: 34, total: 50 },
    categorySlug: 'tivi-loa',
    isHotDeal: true,
    sku: 'TV-SAM-001',
  },
  {
    id: 'appliance-2',
    name: 'LG Door-in-Door 601L InstaView',
    modelNumber: 'InstaView 601L',
    brand: 'LG',
    slug: 'lg-door-in-door-601l-instaview',
    imageUrl: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80',
    originalPrice: 60550000,
    salePrice: 42990000,
    discountPercent: 29,
    installmentBadge: 'Trả góp 0%',
    energyRating: 5,
    giftNote: 'Tặng Nồi chiên không dầu Lock&Lock 5.2L',
    specs: [
      { key: 'Dung tích', value: '601 Lít' },
      { key: 'Động cơ', value: 'Linear Inverter tiết kiệm điện' },
      { key: 'Cửa kính', value: 'InstaView gõ 2 lần sáng đèn' },
    ],
    stockProgress: { sold: 19, total: 25 },
    categorySlug: 'tu-lanh',
    isHotDeal: true,
    sku: 'GD-LG-002',
  },
  {
    id: 'appliance-3',
    name: 'Panasonic Giant 8.5kg NA-F85V1',
    modelNumber: 'NA-F85V1',
    brand: 'Panasonic',
    slug: 'panasonic-giant-8-5kg-na-f85v1',
    imageUrl: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=600&auto=format&fit=crop&q=80',
    originalPrice: 20250000,
    salePrice: 14990000,
    discountPercent: 26,
    installmentBadge: 'Trả góp 0%',
    energyRating: 5,
    giftNote: 'Tặng Giàn phơi thông minh + Nước giặt OMO 4.2kg',
    specs: [
      { key: 'Khối lượng', value: '8.5 kg giặt' },
      { key: 'Công nghệ', value: 'Mâm giặt Active Wave đa chiều' },
      { key: 'Động cơ', value: 'Inverter vận hành êm ái' },
    ],
    stockProgress: { sold: 42, total: 50 },
    categorySlug: 'may-giat',
    isHotDeal: true,
    sku: 'GD-PAN-002',
  },
  {
    id: 'appliance-4',
    name: 'Panasonic Inverter 1.5 HP CU/CS-U12XK',
    modelNumber: 'CU/CS-U12XK',
    brand: 'Panasonic',
    slug: 'panasonic-inverter-1-5-hp-cu-cs-u12xk',
    imageUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&auto=format&fit=crop&q=80',
    originalPrice: 14990000,
    salePrice: 12990000,
    discountPercent: 13,
    installmentBadge: 'Trả góp 0%',
    energyRating: 5,
    giftNote: 'Miễn phí công lắp đặt + 5m ống đồng',
    specs: [
      { key: 'Công suất', value: '1.5 HP (12.000 BTU)' },
      { key: 'Lọc khí', value: 'Nanoe™ X khử mùi ức chế vi khuẩn' },
      { key: 'Làm lạnh', value: 'iAUTO-X làm lạnh nhanh' },
    ],
    stockProgress: { sold: 68, total: 80 },
    categorySlug: 'dieu-hoa',
    sku: 'GD-PAN-001',
  },
  {
    id: 'appliance-5',
    name: 'Sony Bravia 4K 55 inch XR-55A80L',
    modelNumber: 'XR-55A80L',
    brand: 'Sony',
    slug: 'sony-bravia-4k-55-inch-xr-55a80l',
    imageUrl: 'https://images.unsplash.com/photo-1552975084-6e027cd345c2?w=600&auto=format&fit=crop&q=80',
    originalPrice: 34990000,
    salePrice: 28990000,
    discountPercent: 17,
    installmentBadge: 'Trả góp 0%',
    energyRating: 5,
    giftNote: 'Gói ứng dụng VieON VIP + Galaxy Play 12 tháng',
    specs: [
      { key: 'Kích thước', value: '55 inch 4K' },
      { key: 'Bộ xử lý', value: 'Cognitive Processor XR' },
      { key: 'Âm thanh', value: 'Acoustic Surface Audio+' },
    ],
    stockProgress: { sold: 27, total: 40 },
    categorySlug: 'tivi-loa',
    sku: 'TV-SON-001',
  },
  {
    id: 'appliance-6',
    name: 'LG Inverter 2 HP B19END',
    modelNumber: 'B19END',
    brand: 'LG',
    slug: 'lg-inverter-2-hp-b19end',
    imageUrl: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=600&auto=format&fit=crop&q=80',
    originalPrice: 19990000,
    salePrice: 16990000,
    discountPercent: 15,
    installmentBadge: 'Trả góp 0%',
    energyRating: 5,
    giftNote: 'Tặng Bộ vệ sinh điều hòa chuyên dụng',
    specs: [
      { key: 'Công suất', value: '2 HP (18.000 BTU)' },
      { key: 'Công nghệ', value: 'Dual Inverter tiết kiệm điện 70%' },
      { key: 'Gas lạnh', value: 'R32 làm lạnh nhanh 40%' },
    ],
    stockProgress: { sold: 45, total: 60 },
    categorySlug: 'dieu-hoa',
    isHotDeal: true,
    sku: 'GD-LG-001',
  },
  {
    id: 'appliance-7',
    name: 'LG OLED evo 4K 55 inch C4',
    modelNumber: 'OLED55C4',
    brand: 'LG',
    slug: 'lg-oled-evo-4k-55-inch-c4',
    imageUrl: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&auto=format&fit=crop&q=80',
    originalPrice: 38990000,
    salePrice: 32990000,
    discountPercent: 15,
    installmentBadge: 'Trả góp 0%',
    energyRating: 5,
    giftNote: 'Tặng Giá treo tivi thông minh cao cấp',
    specs: [
      { key: 'Kích thước', value: '55 inch OLED evo 4K' },
      { key: 'Bộ xử lý', value: 'α9 AI Gen7 4K' },
      { key: 'Tần số quét', value: '144Hz Dolby Vision' },
    ],
    stockProgress: { sold: 16, total: 30 },
    categorySlug: 'tivi-loa',
    sku: 'TV-LG-001',
  },
  {
    id: 'appliance-8',
    name: 'JBL PartyBox 310',
    modelNumber: 'PartyBox 310',
    brand: 'JBL',
    slug: 'jbl-partybox-310',
    imageUrl: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&auto=format&fit=crop&q=80',
    originalPrice: 16990000,
    salePrice: 14990000,
    discountPercent: 12,
    installmentBadge: 'Trả góp 0%',
    energyRating: 5,
    giftNote: 'Tặng 02 Micro không dây JBL chính hãng',
    specs: [
      { key: 'Công suất', value: '240W uy lực' },
      { key: 'Hiệu ứng', value: 'Đèn LED RGB theo điệu nhạc' },
      { key: 'Thời lượng pin', value: 'Pin khủng 18 giờ liên tục' },
    ],
    stockProgress: { sold: 29, total: 35 },
    categorySlug: 'tivi-loa',
    sku: 'AT-JBL-001',
  },
]

