// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineSupermarket.Infrastructure.Persistence;

#nullable disable

namespace OnlineSupermarket.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260807082824_InitialFoundation")]
    partial class InitialFoundation : Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OnlineSupermarket.Domain.Branches.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Catalog.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("varchar(140)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("brands", (string)null);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Catalog.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("parent_category_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("varchar(140)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_price");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("char(36)")
                        .HasColumnName("brand_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sku");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("varchar(220)")
                        .HasColumnName("slug");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("district");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("recipient_name");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("street");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ward");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsDefault");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Identity.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at_utc");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("UserId");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("char(36)")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAtUtc");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Status", "Role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Intelligence.DemandForecast", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("ActualDataDays")
                        .HasColumnType("int")
                        .HasColumnName("actual_data_days");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("algorithm_version");

                    b.Property<Guid>("BranchInventoryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("branch_inventory_id");

                    b.Property<string>("DataQuality")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("data_quality");

                    b.Property<DateOnly>("ForecastEndDate")
                        .HasColumnType("date")
                        .HasColumnName("forecast_end_date");

                    b.Property<DateOnly>("ForecastStartDate")
                        .HasColumnType("date")
                        .HasColumnName("forecast_start_date");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("generated_at_utc");

                    b.Property<int>("HorizonDays")
                        .HasColumnType("int")
                        .HasColumnName("horizon_days");

                    b.Property<Guid>("JobRunId")
                        .HasColumnType("char(36)")
                        .HasColumnName("job_run_id");

                    b.Property<decimal>("PredictedQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("predicted_quantity");

                    b.HasKey("Id");

                    b.HasIndex("BranchInventoryId");

                    b.HasIndex("JobRunId", "BranchInventoryId", "HorizonDays")
                        .IsUnique()
                        .HasDatabaseName("ix_demand_forecasts_run_inventory_horizon");

                    b.ToTable("demand_forecasts", null, t =>
                        {
                            t.HasCheckConstraint("ck_demand_forecasts_actual_data_days", "actual_data_days + 0 >= 0 AND actual_data_days <= 28");

                            t.HasCheckConstraint("ck_demand_forecasts_horizon", "horizon_days IN (7, 14)");

                            t.HasCheckConstraint("ck_demand_forecasts_predicted_quantity", "predicted_quantity + 0 >= 0");
                        });
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Inventory.BranchInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("char(36)")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)")
                        .HasColumnName("product_id");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int")
                        .HasColumnName("quantity_on_hand");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int")
                        .HasColumnName("reorder_level");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("int")
                        .HasColumnName("reserved_quantity");

                    b.Property<decimal>("SellingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("selling_price");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("BranchId", "ProductId")
                        .IsUnique();

                    b.ToTable("branch_inventories", (string)null);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Inventory.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("BranchInventoryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("branch_inventory_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("note");

                    b.Property<string>("OperationKey")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)")
                        .HasColumnName("operation_key");

                    b.Property<int>("QuantityOnHandAfter")
                        .HasColumnType("int")
                        .HasColumnName("quantity_on_hand_after");

                    b.Property<int>("QuantityOnHandDelta")
                        .HasColumnType("int")
                        .HasColumnName("quantity_on_hand_delta");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("reference_type");

                    b.Property<int>("ReservedQuantityAfter")
                        .HasColumnType("int")
                        .HasColumnName("reserved_quantity_after");

                    b.Property<int>("ReservedQuantityDelta")
                        .HasColumnType("int")
                        .HasColumnName("reserved_quantity_delta");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("OperationKey")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_transactions_operation_key");

                    b.HasIndex("BranchInventoryId", "CreatedAtUtc")
                        .HasDatabaseName("ix_inventory_transactions_inventory_created");

                    b.ToTable("inventory_transactions", (string)null);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Jobs.BackgroundJobRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("char(36)")
                        .HasColumnName("branch_id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("error_summary");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("job_name");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<string>("LockKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("lock_key");

                    b.Property<string>("LockToken")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("lock_token");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("JobName", "LockKey")
                        .IsUnique();

                    b.ToTable("background_job_runs", (string)null);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("char(36)")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("DeliveryAddressId")
                        .HasColumnType("char(36)")
                        .HasColumnName("delivery_address_id");

                    b.Property<string>("DeliveryAddressSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delivery_address_snapshot");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<string>("FulfillmentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("fulfillment_type");

                    b.Property<string>("PromotionCodeSnapshot")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("promotion_code_snapshot");

                    b.Property<Guid?>("PromotionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("promotion_id");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("recipient_name");

                    b.Property<string>("RecipientPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("recipient_phone");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("shipping_fee");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_orders_created");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_orders_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_orders_user_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("line_total");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sku");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Orders.OrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("from_status");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("note");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)")
                        .HasColumnName("order_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("to_status");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_status_histories_order_id");

                    b.ToTable("order_status_histories", (string)null);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("method");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)")
                        .HasColumnName("order_id");

                    b.Property<string>("ProviderResponse")
                        .HasColumnType("text")
                        .HasColumnName("provider_response");

                    b.Property<string>("ProviderTransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("provider_transaction_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_payments_order_id");

                    b.HasIndex("ProviderTransactionId")
                        .HasDatabaseName("ix_payments_provider_tx_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Payments.PaymentCallback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("external_event_id");

                    b.Property<bool>("IsValidSignature")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_valid_signature");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("payment_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("provider");

                    b.Property<string>("RawResponse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_response");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("result_status");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId");

                    b.HasIndex("Provider", "ExternalEventId")
                        .IsUnique()
                        .HasDatabaseName("ix_payment_callbacks_provider_event");

                    b.ToTable("payment_callbacks", (string)null);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Promotions.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount_value");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<decimal>("MinOrderAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("min_order_amount");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int")
                        .HasColumnName("usage_count");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int")
                        .HasColumnName("usage_limit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_promotions_code");

                    b.ToTable("promotions", (string)null);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Recommendations.ProductViewEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("AnonymousSessionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("anonymous_session_id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("char(36)")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)")
                        .HasColumnName("product_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("ViewedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("viewed_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("AnonymousSessionId", "ViewedAtUtc")
                        .HasDatabaseName("ix_product_view_events_anonymous_viewed");

                    b.HasIndex("ProductId", "ViewedAtUtc")
                        .HasDatabaseName("ix_product_view_events_product_viewed");

                    b.HasIndex("UserId", "ViewedAtUtc")
                        .HasDatabaseName("ix_product_view_events_user_viewed");

                    b.ToTable("product_view_events", (string)null);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Recommendations.RecommendationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("algorithm_version");

                    b.Property<string>("AudienceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("audience_key");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("generated_at_utc");

                    b.Property<Guid>("JobRunId")
                        .HasColumnType("char(36)")
                        .HasColumnName("job_run_id");

                    b.Property<int>("Rank")
                        .HasColumnType("int")
                        .HasColumnName("rank");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("RecommendedProductId")
                        .HasColumnType("char(36)")
                        .HasColumnName("recommended_product_id");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("scope");

                    b.Property<decimal>("Score")
                        .HasPrecision(12, 6)
                        .HasColumnType("decimal(12,6)")
                        .HasColumnName("score");

                    b.Property<Guid?>("SourceProductId")
                        .HasColumnType("char(36)")
                        .HasColumnName("source_product_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RecommendedProductId");

                    b.HasIndex("SourceProductId");

                    b.HasIndex("UserId");

                    b.HasIndex("JobRunId", "AudienceKey", "RecommendedProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_recommendation_results_run_audience_product");

                    b.ToTable("recommendation_results", (string)null);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Reviews.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("char(36)")
                        .HasColumnName("order_item_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)")
                        .HasColumnName("product_id");

                    b.Property<sbyte>("Rating")
                        .HasColumnType("tinyint")
                        .HasColumnName("rating");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_reviews_order_item_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reviews_user_id");

                    b.HasIndex("ProductId", "CreatedAtUtc")
                        .HasDatabaseName("ix_reviews_product_created");

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasCheckConstraint("ck_reviews_rating", "rating >= 1 AND rating <= 5");
                        });
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Shopping.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("char(36)")
                        .HasColumnName("branch_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_carts_user_id");

                    b.HasIndex("UserId", "BranchId")
                        .IsUnique()
                        .HasDatabaseName("ix_carts_user_branch");

                    b.ToTable("carts", (string)null);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Shopping.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchInventoryId")
                        .HasColumnType("char(36)")
                        .HasColumnName("branch_inventory_id");

                    b.Property<Guid>("CartId")
                        .HasColumnType("char(36)")
                        .HasColumnName("cart_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("CartId")
                        .HasDatabaseName("ix_cart_items_cart_id");

                    b.ToTable("cart_items", (string)null);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Catalog.Category", b =>
                {
                    b.HasOne("OnlineSupermarket.Domain.Catalog.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Catalog.Product", b =>
                {
                    b.HasOne("OnlineSupermarket.Domain.Catalog.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineSupermarket.Domain.Catalog.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("OnlineSupermarket.Domain.Identity.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OnlineSupermarket.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Intelligence.DemandForecast", b =>
                {
                    b.HasOne("OnlineSupermarket.Domain.Inventory.BranchInventory", null)
                        .WithMany()
                        .HasForeignKey("BranchInventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineSupermarket.Domain.Jobs.BackgroundJobRun", null)
                        .WithMany()
                        .HasForeignKey("JobRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Inventory.BranchInventory", b =>
                {
                    b.HasOne("OnlineSupermarket.Domain.Branches.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineSupermarket.Domain.Catalog.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Inventory.InventoryTransaction", b =>
                {
                    b.HasOne("OnlineSupermarket.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OnlineSupermarket.Domain.Inventory.BranchInventory", null)
                        .WithMany()
                        .HasForeignKey("BranchInventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Jobs.BackgroundJobRun", b =>
                {
                    b.HasOne("OnlineSupermarket.Domain.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Orders.OrderItem", b =>
                {
                    b.HasOne("OnlineSupermarket.Domain.Orders.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Orders.OrderStatusHistory", b =>
                {
                    b.HasOne("OnlineSupermarket.Domain.Orders.Order", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Payments.Payment", b =>
                {
                    b.HasOne("OnlineSupermarket.Domain.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Payments.PaymentCallback", b =>
                {
                    b.HasOne("OnlineSupermarket.Domain.Payments.Payment", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Recommendations.ProductViewEvent", b =>
                {
                    b.HasOne("OnlineSupermarket.Domain.Branches.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OnlineSupermarket.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineSupermarket.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Recommendations.RecommendationResult", b =>
                {
                    b.HasOne("OnlineSupermarket.Domain.Jobs.BackgroundJobRun", null)
                        .WithMany()
                        .HasForeignKey("JobRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineSupermarket.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("RecommendedProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineSupermarket.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("SourceProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OnlineSupermarket.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Reviews.Review", b =>
                {
                    b.HasOne("OnlineSupermarket.Domain.Orders.OrderItem", null)
                        .WithMany()
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineSupermarket.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineSupermarket.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Shopping.CartItem", b =>
                {
                    b.HasOne("OnlineSupermarket.Domain.Shopping.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Orders.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("OnlineSupermarket.Domain.Shopping.Cart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}





